USE COLLEGE;

DELIMITER &&
CREATE PROCEDURE AddStudent(
NAME VARCHAR(100) ,
DOB DATE,
ADDRESS VARCHAR(100),
PHONE_NO BIGINT ,
GENDER VARCHAR(1),
SEMESTER INT,
COURSE_ID INT 
) 
BEGIN
	INSERT INTO STUDENT(NAME ,DOB,ADDRESS,PHONE_NO,GENDER,SEMESTER,COURSE_ID)
    VALUES(NAME ,DOB,ADDRESS,PHONE_NO,GENDER,SEMESTER,COURSE_ID);
END &&

DELIMITER &&
CREATE PROCEDURE AddGradePay(
GRADE_NAME VARCHAR(30) ,
BASIC_PAY INT ,
HRA INT,
DA INT
) 
BEGIN
	INSERT INTO GRADE_PAY(GRADE_NAME,BASIC_PAY,HRA,DA)
    VALUES(GRADE_NAME,BASIC_PAY,HRA,DA);
END &&

DELIMITER &&
CREATE PROCEDURE AddDept(
DEPT_NAME VARCHAR(100) ,
LOCATION VARCHAR(100)
) 
BEGIN
	INSERT INTO DEPT(DEPT_NAME,LOCATION)
    VALUES(DEPT_NAME,LOCATION);
END &&

DELIMITER &&
CREATE PROCEDURE AddFaculty(
FAC_NAME VARCHAR(30) ,
DOB DATE,
EXPERIENCE INT,
ADDRESS VARCHAR(100),
GENDER VARCHAR(1),
GRADE_ID INT
) 
BEGIN
	INSERT INTO FACULTY(FAC_NAME,DOB,EXPERIENCE,ADDRESS,GENDER,GRADE_ID)
    VALUES(FAC_NAME,DOB,EXPERIENCE,ADDRESS,GENDER,GRADE_ID);
END &&

DELIMITER &&
CREATE PROCEDURE AddCourse(
COURSE_NAME VARCHAR(30),
DEPT_ID INT,
CREDITS INT,
DURATION INT
) 
BEGIN
	INSERT INTO COURSE(COURSE_NAME,DEPT_ID,CREDITS,DURATION)
    VALUES(COURSE_NAME,DEPT_ID,CREDITS,DURATION);
END &&

DELIMITER &&
CREATE PROCEDURE AddSubject(
SUB_NAME VARCHAR(100)
) 
BEGIN
	INSERT INTO SUBJECT(SUB_NAME)
    VALUES(SUB_NAME);
END &&


DELIMITER &&
CREATE PROCEDURE AddHostel(
HOSTEL_NAME VARCHAR(5) ,
WARDEN_ID INT,
CAPACITY INT,
CATEGORY VARCHAR(30)
) 
BEGIN
	INSERT INTO HOSTEL(HOSTEL_NAME,WARDEN_ID,CAPACITY,CATEGORY)
    VALUES(HOSTEL_NAME,WARDEN_ID,CAPACITY,CATEGORY);
END &&
