CREATE DATABASE College;
USE COLLEGE;

CREATE TABLE STUDENT(
ROLL_NO INT AUTO_INCREMENT,
CONSTRAINT ROLLNO_PK PRIMARY KEY(ROLL_NO),
NAME VARCHAR(100) NOT NULL,
DOB DATE,
ADDRESS VARCHAR(100),
PHONE_NO BIGINT ,
CONSTRAINT PHONE_U UNIQUE(PHONE_NO),
GENDER VARCHAR(1),
SEMESTER INT NOT NULL,
COURSE_ID INT ,
CONSTRAINT COURSEID_FK FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE GRADE_PAY(
GRADE_ID INT AUTO_INCREMENT,
CONSTRAINT GRADEID_PK PRIMARY KEY(GRADE_ID),
GRADE_NAME VARCHAR(30) NOT NULL,
BASIC_PAY INT NOT NULL,
HRA INT,
DA INT
);

CREATE TABLE DEPT(
DEPT_ID INT AUTO_INCREMENT,
CONSTRAINT DEPTID_PK PRIMARY KEY(DEPT_ID),
DEPT_NAME VARCHAR(100) NOT NULL,
LOCATION VARCHAR(100)
);

CREATE TABLE FACULTY(
FAC_ID INT AUTO_INCREMENT,
CONSTRAINT FACID_PK PRIMARY KEY(FAC_ID), 
FAC_NAME VARCHAR(30) NOT NULL,
DOB DATE,
EXPERIENCE INT,
ADDRESS VARCHAR(100),
GENDER VARCHAR(1),
GRADE_ID INT,
CONSTRAINT GRADEID_FK FOREIGN KEY(GRADE_ID) REFERENCES GRADE_PAY(GRADE_ID)
);

CREATE TABLE TEACHING_FAC(
FAC_ID INT,
CONSTRAINT FACID_PK1 PRIMARY KEY(FAC_ID), 
CONSTRAINT FACID_FK FOREIGN KEY(FAC_ID) REFERENCES FACULTY(FAC_ID),
DEPT_ID INT,
CONSTRAINT DEPTID_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPT(DEPT_ID),
QUALIFICATION VARCHAR(30)
);

CREATE TABLE NON_TEACHING_FAC(
FAC_ID INT,
CONSTRAINT FACID_PK2 PRIMARY KEY(FAC_ID), 
CONSTRAINT FACID_FK1 FOREIGN KEY(FAC_ID) REFERENCES FACULTY(FAC_ID),
DESIGNATION VARCHAR(30)
);

CREATE TABLE HOD(
HOD_ID INT,
CONSTRAINT HODID_PK PRIMARY KEY(HOD_ID), 
CONSTRAINT FACID_FK2 FOREIGN KEY(HOD_ID) REFERENCES FACULTY(FAC_ID),
DEPT_ID INT,
CONSTRAINT DEPTID_FK1 FOREIGN KEY(DEPT_ID) REFERENCES DEPT(DEPT_ID)
);

CREATE TABLE DEANS(
DEAN_ID INT,
CONSTRAINT DEANID_PK PRIMARY KEY(DEAN_ID), 
CONSTRAINT FACID_FK3 FOREIGN KEY(DEAN_ID) REFERENCES FACULTY(FAC_ID),
DESIGNATION VARCHAR(100) NOT NULL,
EMAIL_ID VARCHAR(100),
CONSTRAINT EMAIL_U UNIQUE(EMAIL_ID),
OFFICE_CONTACT INT,
CONSTRAINT CONTACT_U UNIQUE(OFFICE_CONTACT)
);

CREATE TABLE DIRECTORATE(
DIR_ID INT,
CONSTRAINT DIRID_PK PRIMARY KEY(DIR_ID), 
CONSTRAINT FACID_FK4 FOREIGN KEY(DIR_ID) REFERENCES FACULTY(FAC_ID),
DESIGNATION VARCHAR(30),
EMAIL_ID VARCHAR(100),
CONSTRAINT EMAIL_U1 UNIQUE(EMAIL_ID),
OFFICE_CONTACT INT,
CONSTRAINT CONTACT_U1 UNIQUE(OFFICE_CONTACT)
);

CREATE TABLE COURSE(
COURSE_ID INT AUTO_INCREMENT,
CONSTRAINT COURSEID_PK PRIMARY KEY(COURSE_ID),
COURSE_NAME VARCHAR(30) NOT NULL,
DEPT_ID INT,
CONSTRAINT DEPTID_FK2 FOREIGN KEY(DEPT_ID) REFERENCES DEPT(DEPT_ID),
CREDITS INT,
DURATION INT
);

CREATE TABLE SUBJECT(
SUB_ID INT AUTO_INCREMENT,
CONSTRAINT SUBID_PK PRIMARY KEY(SUB_ID),
SUB_NAME VARCHAR(100)
);

CREATE TABLE COURSE_SUBJECT(
COURSE_ID INT,
CONSTRAINT COURSEID_FK1 FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID),
SUB_ID INT,
CONSTRAINT SUBID_FK FOREIGN KEY(SUB_ID) REFERENCES SUBJECT(SUB_ID),
CONSTRAINT COURSESUBJECT_PK PRIMARY KEY(COURSE_ID,SUB_ID),
SEMESTER INT
);

CREATE TABLE HOSTEL(
HOSTEL_ID INT AUTO_INCREMENT,
CONSTRAINT HOSTELID_PK PRIMARY KEY(HOSTEL_ID),
HOSTEL_NAME VARCHAR(5) NOT NULL,
CONSTRAINT HNAME_U UNIQUE(HOSTEL_NAME),
WARDEN_ID INT,
CONSTRAINT FACID_FK6 FOREIGN KEY(WARDEN_ID) REFERENCES FACULTY(FAC_ID),
CAPACITY INT,
CATEGORY VARCHAR(30),
CONSTRAINT CATEGORY_C CHECK(CATEGORY IN ('GIRLS','BOYS'))
);

CREATE TABLE ALLOCATED_HOSTEL(
ROLL_NO INT,
CONSTRAINT ROLLNO_PK1 PRIMARY KEY(ROLL_NO),
CONSTRAINT ROLLNO_FK FOREIGN KEY(ROLL_NO) REFERENCES STUDENT(ROLL_NO),
HOSTEL_ID INT,
CONSTRAINT HOSTELID_FK FOREIGN KEY(HOSTEL_ID) REFERENCES HOSTEL(HOSTEL_ID),
ROOM_OCCUPANCY VARCHAR(15),
CONSTRAINT ROOMOCCP_C CHECK(ROOM_OCCUPANCY IN ('1S','2S','3S')),
ROOM_TYPE VARCHAR(15),
CONSTRAINT ROOMTYPE_C CHECK(ROOM_TYPE IN ('AC','NON-AC'))
);

CREATE TABLE RESULT(
ROLL_NO INT,
CONSTRAINT ROLLNO_FK1 FOREIGN KEY(ROLL_NO) REFERENCES STUDENT(ROLL_NO),
SEMESTER INT ,
CONSTRAINT ROLLSEM_PK PRIMARY KEY(ROLL_NO,SEMESTER),
SGPA FLOAT NOT NULL,
CONSTRAINT SGPA_C CHECK(SGPA<=10),
CGPA FLOAT NOT NULL,
CONSTRAINT CGPA_C CHECK(CGPA<=10)
);
